name = "heimdall-poc"
version = "1.0.0"
content_type = "json"

[deployment]
nodes = 1
permissions = ["https://sepolia.infura.io", "https://dweb.link"]

[build]
dir = "build"
entry = "heimdall-poc_debug.wasm"
command = "yarn run build:debug"

[build_release]
dir = "build"
entry = "heimdall-poc.wasm"
command = "yarn run build:release"
